### ISSUE TITLE
Flying snoo broke

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#13]
Not sure if we messed up with the css or if the method we used to place a block on the bottom of reddit no longer works. Anyway, the `tb-footer-block` needs to be fixed.

**Comment by Geo1088** [comment]
The footer block needs to be inserted in overlays, which have their own scroll containers. With infinite scroll, the footer block is otherwise never shown.

I'm not sure if there's a good way to do this or not. Do we get an API event for the overlay opening? If not, we'll probably have to hack it based on a post event where the event target is inside the overlay element.

As of right now at least, `#overlayScrollContainer` is the selector for the overlay container. Adding the footer there manually from the inspector creates the space at the bottom of the overlay and ensures that the bottombar has space, but the actual flyingsnoo behavior is a bit buggy.

**Comment by creesch** [comment]
Eh, it works most of the time. Calling this one fixed.
