### ISSUE TITLE
request handler is bad at invalidated tokens

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#145]
If a user's old modmail token isn't refreshed in a while, it'll go bad, and the current method we have of detecting this seems to not work very well. The solution is to re-open old modmail, which regenerates the token cookie and then toolbox works again.

Oauth is a pain man.

https://www.reddit.com/r/toolbox/comments/dck5aa/unable_to_lock_posts/

https://www.reddit.com/r/toolbox/comments/dcm0kl/unable_to_lock_comments_on_old_reddit/

**Comment by creesch** [comment]
For locking posts the simplest solution is to switch back to the regular api calls. There is no real need for it to use the oauth flow. 

For the longer term it seems like we need to figure out if a token is still valid :/

**Comment by creesch** [comment]
Well do'h cookies haven an expiry date, all we probably need to do is check that before doing the call.

**Comment by creesch** [comment]
Assigned myself, should be a relative easy fix and done for the next release.

**Comment by creesch** [comment]
Likely fixed in cc504271a4406405bb1ac6c8c259055490142227 but difficult to tell, when I started I also got some 401 errors I couldn't place. 

I also switched the cookie url check to actually check `mod.reddit.com` instead of `www.reddit.com` which also had the token cookie but at the time of testing one that shouldn't be expired while when I checked `mod.reddit.com` it appeared to have a different value.
