### ISSUE TITLE
modmail preview: fix relative urls

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#261]
When typing /r/sub or /u/user clicking on them doesn't work as we are in the `mod` subdomain.

**Comment by Geo1088** [comment]
This will be a bit of a pain to work on because Snuownd doesn't have any flag or option for outputting fully-qualified URLs for these. Our options are either to fork Snuownd and add that functionality ourselves, or write some jank regex substitution to add `https://www.reddit.com` to the beginning of all generated `href`s that start with `/`.

**Comment by Geo1088** [comment]
We could probably fix this for 5.3.1 if we just do it the jank way, `.replace('href="/r/', 'href="https://www.reddit.com/r/').replace('href="/u/', 'href="https://www.reddit.com/user/')`

Thoughts?

**Comment by SpyTec** [comment]
Not really a jank way, but yeah. Simple regex replace would suffice

**Comment by creesch** [comment]
afaik you can't type relative urls from modmail normally so we can just replace ` href="/`, right?

**Comment by creesch** [comment]
though people can manually I suppose...

**Comment by Geo1088** [comment]
Actually yeah, that does make sense, just `.replace(/href="/g, 'href="https://www.reddit.com/')` should do the trick. Relative URLs I don't think we need to worry about.

**Comment by SpyTec** [comment]
Right it's relative URLs.. Reddit makes these links full-links after submission

![image](https://user-images.githubusercontent.com/6598829/77259080-4e635300-6c7f-11ea-9969-8a6fc998261e.png)
