### ISSUE TITLE
QT: Ignore reports for selected items

### ISSUE THREAD

**Issue by eritbh** [toolbox-team/reddit-moderator-toolbox#311]
Just like the existing buttons for approving and removing things, should be able to ignore reports on all selected items.

**Comment by Endercheif** [comment]
Hey there. Can I work on this issue?

**Comment by eritbh** [comment]
Go for it! Let us know if you have any questions here or on Discord (linked in the readme).

**Comment by Endercheif** [comment]
![image](https://user-images.githubusercontent.com/45527309/196005203-291c75f9-ca98-4ab1-bcdb-4cd64751636a.png)
I have got it working ~~after spending way too long debugging because I typed `ud` instead of `uh`~~! Last thing is classes/styling.
With reference to the image the other buttons have the classes `negative`, `neutral` and `positive` respectively.

Do I add a class such as `ignore` to the ignore button?
If so do I also add an `ignored` class and update logic in the following places?
[queuetools.js#L669](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/4a40f68c7c6598b20fce6f3bc7b99dc92aa4fb02/extension/data/modules/queuetools.js#L669) [queuetools.js#L653-L654](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/4a40f68c7c6598b20fce6f3bc7b99dc92aa4fb02/extension/data/modules/queuetools.js#L653-L654)
and what colour is good for the button?

**Comment by eritbh** [comment]
Oh weird, I didn't realize we were actually using the `.negative`/`.neutral`/`.positive` classes on those buttons to do the logic - I thought they were appearance-only. I would go with an `.ignore` class for the button yeah.

I don't think we have any particular styling we want to apply to posts with reports ignored, so I don't know if there's any class we need to add to the `$actioned` post in that case. @creesch can correct me if I'm wrong though.

If you've got the feature mostly working, feel free to send a PR now and we can discuss more in review comments.
