### ISSUE TITLE
Add a user-accessible permalink to modmail threads as a private moderator note

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#322]
One of the more annoying issues in new modmail is that you can't share links of previous modmails with non-moderators (e.g., `Please refer to our previous conversation about this [here](...).`"). The mod.reddit.com links do not work for users.

I don't think the ID or permalink shows up anywhere in the source, unfortunately (a way to access that would be the easy fix), but if you are the moderator that **sent** a modmail reply (either as the subreddit or as yourself), the permalink is available in your sent mail.

A great enhancement would be as follows:

1. When any reply is sent in new modmail, scan the thread for a private note with a modmail link to that thread. If there is one already, do nothing. If there isn't one then add a new private note right after the message is sent. Ideally, follow the parent chain so the permalink is for the original modmail that started a particular thread.

2. Toolbox-added private notes of permalinks would follow a specific format like:

       [user-accessible link to this modmail thread](https://www.reddit.com/message/messages/wowwow) (added by Toolbox)

Only adding one note will help keep threads from being too cluttered and it will also help that you only really need one moderator using Toolbox to make a reply for the entire thread to have a solid link that can be shared with the user in the event that the thread needs to be referred to in the future. Yes, some threads may have only had moderators on mobile, but 95% of our modmail is handled by people on their computer so that's not really a major issue.

**Comment by Geo1088** [comment]
This is a great idea. I've been meaning to find a solution for this in the past as well, getting the user-accessible permalink from your sent messages is a clever solution.

I think this will need some consideration about how best to implement it in Toolbox; I'm a bit weary of injecting what is essentially machine-readable metadata into a modmail conversation, which isn't really made for that sort of thing. Using a specific format to store the link is definitely possible technically, but it feels like a bit of a messy solution, and I'd like to see if there's any other way around it first.

In the past, I've worked around this issue by just sending a reply to the old thread so it surfaces in the user's inbox. I'm wondering if something like that would work too, since it would avoid having to cache information in the modmail itself.

**Comment by dequeued0** [comment]
It looks like a new field named `legacy_first_message_id` has been added to new modmail threads. I think it would suffice to close out this issue to add a "permalink"-labeled link based on that field.

**Comment by SpyTec** [comment]
So it seems! 🎉 

I don't see why they'd add the field to the API without themselves doing something as well. We can certainly add this feature for next release if they haven't added it by then

**Comment by dequeued0** [comment]
Nevermind! Apparently, there is already a link next to the thread title. It was darn hard to notice in dark mode, but I see it now that it was pointed out to me by someone. I'm closing this bug.
