### ISSUE TITLE
Explore the possibility of integrating new modmail in the jsapi flow

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#38]
Currently new modmail is the odd one out that basically does a bit of a hybrid thing between old reddit and new reddit. We probably want to integrate it more into the new reddit jsAPI event flow so relevant buttons are easier to implement in new modmail as well. 

Prompted today with me wanting to use the toolbox profile feature in modmail and finding out that we don't have any way to trigger it there. Which is very silly of course.

**Comment by Geo1088** [comment]
I think we can handle this similarly to how we handle the hover card on the redesign. Ideally, we should set up our event faking system to treat the sidebar area as a fake jsapi region, with the same info sent as for the redesign hover card, so that anything added to one is automatically added to the other. We can do the same for the next-to-name stuff, too, and if we handle #110 as well, then I think that'll cover pretty much all the bases for new modmail.
