### ISSUE TITLE
Make profile overlay search accessible via URL options

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#388]
Suggested [here](https://www.reddit.com/r/toolbox/comments/j5rb80/suggestion_add_a_url_argument_to_search_by/). We probably wouldn't want to use a proper query string for this, but doing something similar to the hash fragments RES adds when scrolling through NER pages could probably be doable.

**Comment by creesch** [comment]
Not sure how suitable our current code is for this but we already have some stuff to deal with hash parameters. 

We do have `TBHelpers.getHashParameter` https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbhelpers.js#L625-L641

Modbar uses it to open the settings dialogue https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/modbar.js#L497-L530  (side note, that interval mechanism is a bit odd, we might at one point look at doing that in a different manner possibly hook it into the url change mechanism)

**Comment by creesch** [comment]
Thinking about it, it would be great if we could work it into `TBNewPage` (or at least that area) and make it event based for modules to listen to. Something like `TBHashParams`.

**Comment by creesch** [comment]
To continue my spam (I'll make this the last comment for now), it seems that `browser.tabs.onUpdated` does also trigger on hash changes which is good. So we can probably include something in the newpage trigger like this 

```javascript 
if (window.location.hash) {
        const hash = window.location.hash.substring(1);
        console.log(hash)

        // To make sure we only trigger on toolbox hashes we check that the first param starts with `tb`.
        // This because `tbsettings` is already used for settings. 
        if(hash.startsWith('?tb')) {
            const paramObject = {};
            const params = hash.split('&');
            params.forEach(param => {
                const keyval = param.split('=');
                const key = keyval[0].replace('?', ''),
                      val = keyval[1];

                paramObject[key] = val;
  
            });
            window.dispatchEvent(new CustomEvent('TBHashParams', {detail: contextObject}));
        }
}
```

**Comment by creesch** [comment]
As the hashing mechanism is now implemented I figure I'd start work on this. Before I do however I want to properly work out the parameters used. So far I am thinking about the following 

- `tbprofile` *mandatory* which will be one of `overview`, `comments` or `posts`.  
- `user` *optional* if not given on when on a profile page it will use that user and otherwise give an error message. 
- `subreddit` *optional* when present will initiate a profile search on opening of profile.
- `content` *optional* when present will initiate a profile search on opening of profile.

I also need to take the `Always open toolbox profile overlay on reddit profiles.` setting in account to make sure it doesn't cause any conflicts there. 

Finally in regards to the actual implementation I want to try to avoid adding too much mechanics to specifically make this possible. For example, when initiating search I am planning to input the given params into the actual search fields and submitting the form. 

However to tell `makeProfile()` to init a search I am going to need to add options there.
