### ISSUE TITLE
Match highlighting does not seem to highlight matches in bullet points

### ISSUE THREAD

**Issue by adhesivecheese** [toolbox-team/reddit-moderator-toolbox#488]
Bracketed match terms from automoderator reports do not highlight when appearing inside bullet pointed lists.

**Comment by eritbh** [comment]
The selectors used for highlighting stuff [here](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/queuetools.js#L1091-L1095) seem to rely on the text being in a `<p>`, which isn't guaranteed for lists whose items are not separated by empty lines. For example, the markdown

```md
- a
- b
- c
```

will be rendered as

```html
<div class="md">
  <ul>
    <li>a</li>
    <li>b</li>
    <li>c</li>
  </ul>
</div>
```

@creesch Does the highlight plugin we're working work for nested elements? Can we just run it on the whole `.md` element rather than on `.md p`s specifically?
