### ISSUE TITLE
"Add removal reason" button doesn't show on post removed by automoderator

### ISSUE THREAD

**Issue by amici-ursi** [toolbox-team/reddit-moderator-toolbox#684]
![screenshot 2015-11-19 00 54 41](https://cloud.githubusercontent.com/assets/6052722/11264450/23b8db4c-8e59-11e5-9b48-db5b4cd5b7e1.png)

It's not filtered. If I approve the post, then remove it again; then the "add removal reason" button shows up.

**Comment by agentlame** [comment]
This is apparently by design: 5c93687ffd0f9bba7bc9002528766e6f5af9418e

@creesch ^

**Comment by creesch** [comment]
Hrm... maybe we should do a check on the pretty-buttons instead. If both spam, approve and remove are there it is a filtered post in which case the button should not be present. 

To give it some context, it should only be not visible for filtered posts. Because leaving a removal reason through the button on filtered posts will not actually remove them (since the button only calls the overlay).

**Comment by Geo1088** [comment]
5bee6554d63251dd7a58f53bab065fb723926b7e
